apiVersion: apps/v1
kind: Deployment
metadata:
    name: linker-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: linker-backend
    template:
        metadata:
            labels:
                app: linker-backend
        spec:
            containers:
                - name: linker-backend
                  image: stephano21/linker-backend:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: linker-config
                      - secretRef:
                            name: linker-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: linker-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: linker-frontend
    template:
        metadata:
            labels:
                app: linker-frontend
        spec:
            containers:
                - name: linker-frontend
                  image: stephano21/linker-frontend:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        value: "linker"
                      - name: POSTGRES_PASSWORD
                        value: "linker"
                      - name: POSTGRES_DB
                        value: "linkerdb"
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-storage
                  emptyDir: {}
