apiVersion: v1
kind: Service
metadata:
    name: linker-backend
spec:
    type: NodePort # Cambiado de ClusterIP a NodePort
    selector:
        app: linker-backend
    ports:
        - port: 3000 # puerto interno en el cluster
          targetPort: 3000
          nodePort: 31000 # puerto fijo para tu Mac

---
apiVersion: v1
kind: Service
metadata:
    name: linker-frontend
spec:
    type: NodePort # Cambiado de ClusterIP a NodePort
    selector:
        app: linker-frontend
    ports:
        - port: 80 # puerto interno del contenedor
          targetPort: 80
          nodePort: 30080 # puerto fijo para tu Mac

---
apiVersion: v1
kind: Service
metadata:
    name: db
spec:
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
