apiVersion: apps/v1
kind: Deployment
metadata:
    name: linker-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: linker-frontend
    template:
        metadata:
            labels:
                app: linker-frontend
        spec:
            containers:
                - name: linker-frontend
                  image: stephano21/linker-frontend:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: linker-frontend
spec:
    type: NodePort # Cambiado de ClusterIP a NodePort
    selector:
        app: linker-frontend
    ports:
        - port: 80 # puerto interno del contenedor
          targetPort: 80
          nodePort: 30080 # puerto fijo para tu Mac

