name: CI/CD Linker App

on:
    push:
        branches:
            - gestion_configuracion
    pull_request:
        branches:
            - gestion_configuracion

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: linker
                    POSTGRES_PASSWORD: linker
                    POSTGRES_DB: linkerdb
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Run Backend unit tests
              working-directory: ./Backend
              run: |
                  npm install
                  npm test

            - name: Run Frontend unit tests
              working-directory: ./Frontend
              run: |
                  npm install
                  npm test -- --watch=false --browsers=ChromeHeadless

            - name: Build and push Backend Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./Backend
                  file: ./Backend/Dockerfile
                  push: true
                  tags: stephano21/linker-backend:latest

            - name: Build and push Frontend Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./Frontend
                  file: ./Frontend/Dockerfile
                  push: true
                  tags: stephano21/linker-frontend:latest

            - name: Mostrar archivos del workspace
              run: |
                  echo "Directorio actual: $(pwd)"
                  ls -la
                  ls -la ${{ github.workspace }}

            - name: Deploy with Docker Compose
              working-directory: ${{ github.workspace }}
              run: |
                  docker compose -f docker-compose.yaml up -d --build
                  docker compose ps
